services:
  speech:
    image: speech
    build:
      context: /home/jetson/playa-ai
      dockerfile: /home/jetson/playa-ai/speech/Dockerfile
      secrets:
        - envfile
    container_name: speech
    user: "1000:1000"
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    env_file:
      - .env
    volumes:
      - /home/jetson/playa-ai/speech:/workspace/speech
    restart: unless-stopped

  llm:
    image: llm
    build:
      context: /home/jetson/playa-ai/llm
      dockerfile: /home/jetson/playa-ai/llm/Dockerfile
      secrets:
        - envfile
    container_name: llm
    network_mode: host
    env_file:
      - .env
    restart: unless-stopped

secrets:
  envfile:
    file: .env
